// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SuperSirAntsABot2;

import org.usfirst.frc3244.SuperSirAntsABot2.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.InternalButton;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc3244.SuperSirAntsABot2.subsystems.*;
import org.usfirst.frc3244.SuperSirAntsABot2.util.AndJoystickButton;
import org.usfirst.frc3244.SuperSirAntsABot2.util.AndNOTJoystickButton2;
import org.usfirst.frc3244.SuperSirAntsABot2.util.JoystickAxisButton;
import org.usfirst.frc3244.SuperSirAntsABot2.util.JoystickPOVButton;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick xBox_Driver;
    public Joystick xBox_CoDriver;
    public Joystick launchPad;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
  //Xbox game pad Channels
    public static final int GAMEPAD_XBOX_LEFT_X_AXIS = 0;//
    public static final int GAMEPAD_XBOX_LEFT_Y_AXIS = 1;//
	public static final int GAMEPAD_XBOX_LEFT_TRIGGER = 2;//
	public static final int GAMEPAD_XBOX_RIGHT_TRIGGER = 3;//
	public static final int GAMEPAD_XBOX_RIGHT_X_AXIS = 4;//
	public static final int GAMEPAD_XBOX_RIGHT_Y_AXIS = 5;//

	public static final int GAMEPAD_XBOX_A_BUTTON = 1;//
	public static final int GAMEPAD_XBOX_B_BUTTON = 2;//
	public static final int GAMEPAD_XBOX_X_BUTTON = 3;//
	public static final int GAMEPAD_XBOX_Y_BUTTON = 4;//
	public static final int GAMEPAD_XBOX_LEFT_BUTTON = 5;//
	public static final int GAMEPAD_XBOX_RIGHT_BUTTON = 6;//
	public static final int GAMEPAD_XBOX_RESET_BUTTON = 7;//
	public static final int GAMEPAD_XBOX_START_BUTTON = 8;//
	public static final int GAMEPAD_XBOX_LEFT_STICK_BUTTON = 9;
	public static final int GAMEPAD_XBOX_RIGHT_STICK_BUTTON = 10;
	
	public JoystickButton a_xBox_Driver;
	public JoystickButton b_xBox_Driver;
	public JoystickButton x_xBox_Driver;
	public JoystickButton y_xBox_Driver;
	public JoystickButton lb_xBox_Driver;
	public JoystickButton rb_xBox_Driver;
	public JoystickButton start_xBox_Driver;
	public JoystickButton reset_xBox_Driver;
   
	public JoystickAxisButton rt_xBox_Driver;
   
	public JoystickPOVButton povNorth_xBox_Driver;
	public JoystickPOVButton povSouth_xBox_Driver;
	public JoystickPOVButton povWest_xBox_Driver;
	public JoystickPOVButton povEast_xBox_Driver;
	
   
	public Joystick xbox_xBox_CoDriver;
	public JoystickButton a_xBox_CoDriver;
	public JoystickButton b_xBox_CoDriver;
	public JoystickButton x_xBox_CoDriver;
	public JoystickButton y_xBox_CoDriver;
	public JoystickButton lb_xBox_CoDriver;
	public JoystickButton rb_xBox_CoDriver;
	public JoystickButton start_xBox_CoDriver;
	public JoystickButton reset_xBox_CoDriver;
	private JoystickAxisButton lTrig_xBox_CoDriver;
	private JoystickAxisButton rTrig_xBox_CoDriver;
	
	public JoystickPOVButton povNorth_xBox_CoDriver;
	public JoystickPOVButton povSouth_xBox_CoDriver;
	public JoystickPOVButton povWest_xBox_CoDriver;
	public JoystickPOVButton povEast_xBox_CoDriver;
   
	public JoystickAxisButton rt_xBox_CoDriver;
   
	public JoystickButton btn1_launchPad;
	public JoystickButton btn2_launchPad;
	public JoystickButton btn3_launchPad;
	public JoystickButton btn4_launchPad;
	public JoystickButton btn5_launchPad;
	public JoystickButton btn6_launchPad;
	public JoystickButton btn7_launchPad;
	public JoystickButton btn8_launchPad;
	public JoystickButton btn9_launchPad;
	public JoystickButton btn10_launchPad;
	public JoystickButton btn11_launchPad;
	
	/*
	 *	 	LT							RT
	 * 		LB							LB
	 * 
	 * 									Y
	 * 		N			R	S		X		B
	 * 	w		e						A
	 *		S
	 */
	
   public AndJoystickButton scissor_Left_Motor_Jog;
   public AndJoystickButton scissor_Right_Motor_Jog;
    public OI() {
    	setUp_Controler_xBox_Driver();
    	setUp_Controler_xBox_CoDriver();
    	setUp_Controler_LaunchPad();
    	setUp_SmartDashboard_Buttons();
    	setUp_AND_Buttons(); //Do this after all joy sticks are declared.
    	setUp_OR_Buttons(); //Do this after all joy sticks are declared. 
    	
    }

    private void setUp_Controler_xBox_Driver(){
    	xBox_Driver = new Joystick(0);
    }
    
    private void setUp_Controler_xBox_CoDriver(){
    	xBox_CoDriver = new Joystick(1);
    	
    	a_xBox_CoDriver = new JoystickButton(xBox_CoDriver, GAMEPAD_XBOX_A_BUTTON);
    	//Eliminate the cancle of scissor to setpoint when wrist or intake used
    	//a_xBox_CoDriver.whenPressed(new ScissorSafeLowerToStow());
    	a_xBox_CoDriver.whenPressed(new ScissorToSetpoint(Robot.scissor.DOWN,true));
    	
    	b_xBox_CoDriver = new JoystickButton(xBox_CoDriver, GAMEPAD_XBOX_B_BUTTON);
    	b_xBox_CoDriver.whenPressed(new ScissorToSetpoint(Robot.scissor.SWITCH,true));
    	
    	x_xBox_CoDriver = new JoystickButton(xBox_CoDriver, GAMEPAD_XBOX_X_BUTTON);
    	x_xBox_CoDriver.whenPressed(new ScissorToSetpoint(Robot.scissor.CLIMB,true));
    	
    	y_xBox_CoDriver = new JoystickButton(xBox_CoDriver, GAMEPAD_XBOX_Y_BUTTON);
    	y_xBox_CoDriver.whenPressed(new ScissorToSetpoint(Robot.scissor.SCALE,true));
    	
    	reset_xBox_CoDriver = new JoystickButton(xBox_CoDriver, GAMEPAD_XBOX_RESET_BUTTON);
    	reset_xBox_CoDriver.whenPressed(new Wrist_Up_CommandGroup());
    	
    	start_xBox_CoDriver = new JoystickButton(xBox_CoDriver, GAMEPAD_XBOX_START_BUTTON);
    	start_xBox_CoDriver.whenPressed(new Wrist_Down(1));
    	
    	lTrig_xBox_CoDriver = new JoystickAxisButton(xBox_CoDriver, GAMEPAD_XBOX_LEFT_TRIGGER);
    	//lTrig_xBox_CoDriver.whenPressed(new ScissorSafeLowerToStow());
    	lTrig_xBox_CoDriver.whileHeld(new IntakeCube_CommandGroup());
    	lTrig_xBox_CoDriver.whenReleased(new ScissorToSetpoint(Robot.scissor.DRIVE_WITH_CUBE,true));
    	
    	rTrig_xBox_CoDriver = new JoystickAxisButton(xBox_CoDriver, GAMEPAD_XBOX_RIGHT_TRIGGER);
    	rTrig_xBox_CoDriver.whileHeld(new IntakeLaunch());
    	
    	rb_xBox_CoDriver = new JoystickButton(xBox_CoDriver, 5);
    	rb_xBox_CoDriver.whenPressed(new ScissorToSetpoint(Robot.scissor.DRIVE_WITH_CUBE,true));
    	
    	povWest_xBox_CoDriver = new JoystickPOVButton(xBox_CoDriver, JoystickPOVButton.WEST);
    	povWest_xBox_CoDriver.whileHeld(new Intake_SpinCube());
    	
    	
    }
    
    private void setUp_Controler_LaunchPad(){
    	launchPad = new Joystick(2);
    	
    	
    	
    	btn5_launchPad = new JoystickButton(launchPad, 5);
    	btn5_launchPad.whenPressed(new Intake_Open(1));
    	
    	btn6_launchPad = new JoystickButton(launchPad, 6);
    	btn6_launchPad.whenPressed(new Intake_Close(1));
    	
    	btn7_launchPad = new JoystickButton(launchPad, 7);
    	btn7_launchPad.whileHeld(new IntakeLaunch(-600));
    	
    	btn8_launchPad = new JoystickButton(launchPad, 8);
    	btn8_launchPad.whileHeld(new IntakeLaunch(-400));
    	
    	btn9_launchPad = new JoystickButton(launchPad, 9);
    	btn9_launchPad.whileHeld(new IntakeLaunch(-200));
    	
    	btn11_launchPad = new JoystickButton(launchPad, 11);
    	btn11_launchPad.whenPressed(new ScissorReference_CG());
    	
    }
    private void setUp_SmartDashboard_Buttons(){
    	//example = new InternalButton();
    	//example.whileHeld(new CMD());
    	SmartDashboard.putData("Intake Cube", new IntakeCube());
    	SmartDashboard.putData("Intake Eject", new IntakeLaunch());
    
    	SmartDashboard.putData("Scissor Reference", new ScissorReference_CG());
    	SmartDashboard.putData("Scissor to CLIMB", new ScissorToSetpoint(Robot.scissor.CLIMB,true));
    	SmartDashboard.putData("Scissor to SCALE", new ScissorToSetpoint(Robot.scissor.SCALE,true));
    	SmartDashboard.putData("Scissor to SWITCH", new ScissorToSetpoint(Robot.scissor.SWITCH,true));
    	SmartDashboard.putData("Scissor to DOWN", new ScissorToSetpoint(Robot.scissor.DOWN,true));
    	SmartDashboard.putData("Scissor Hooked and Climb",new Scissor_Climb());
    	
    	SmartDashboard.putData("Winch Unwind Jog",  new Winch_Unwind_Jog());
    	SmartDashboard.putData("Winch Climb",  new Winch_Climb(Winch.TEST_ROTATIONS));
    	SmartDashboard.putData("Extend Hooks", new Winch_Hooks_Extend());
    	SmartDashboard.putData("Retract Hooks", new Winch_Hooks_Retract());
    	
    	SmartDashboard.putData("Wrist Up", new Wrist_Up_CommandGroup());//Wrist_Up(1));
    	SmartDashboard.putData("Wrist Down", new Wrist_Down(1));
    	
    	
    	SmartDashboard.putData("Rollers Open", new Intake_Open(1));
    	SmartDashboard.putData("Rollers Close", new Intake_Close(1));
    	SmartDashboard.putData("Rollers Float", new Intake_Float(1));
    	
    	SmartDashboard.putData("Prep For Climb", new CLIMB_0());
    	SmartDashboard.putData("Lift Robot", new CLIMB_Lift_Robot());
    	
    	
    	
    }
    
    private void setUp_AND_Buttons(){
    	//scissor_Left_Motor_Jog = new AndJoystickButton(xBox_Driver, GAMEPAD_XBOX_A_BUTTON, xBox_Driver, GAMEPAD_XBOX_X_BUTTON);
    	//scissor_Left_Motor_Jog.whileHeld(new Scissor_Jog_Left_Motor());
    	
    	//scissor_Right_Motor_Jog = new AndJoystickButton(xBox_Driver, GAMEPAD_XBOX_A_BUTTON, xBox_Driver, GAMEPAD_XBOX_B_BUTTON);
    	//scissor_Right_Motor_Jog.whileHeld(new Scissor_Jog_Right_Motor());
    }
    private void setUp_OR_Buttons(){
    
    }
    
    private double stickClamp(double value, double min, double max){
    	if(value>max){
    		return max;
    	}else if(value < min){
    		return min;
    	}else{
    		return value;
    	}
    }
    private double stickDeadBand(double value, double deadband){
    	if(Math.abs(value)<deadband){
    		return 0;
    	}else{
    		return value;
    	}
    }
    public double driveX() {
    	if(launchPad.getRawButton(3)) {
    		return(stickDeadBand(xBox_Driver.getRawAxis(GAMEPAD_XBOX_LEFT_X_AXIS),.2));
    	}else {
    		return(stickDeadBand(-xBox_Driver.getRawAxis(GAMEPAD_XBOX_LEFT_X_AXIS),.2));
    	}
    	
	}
	
    //Strife
	public double driveY() {
		// The driveY is the "Y" Axis of the Driver Gamepad.
		// However, the joysticks give -1.0 on the Y axis when pushed forward
		// This method reverses that, so that positive numbers are forward
		if(launchPad.getRawButton(3)) {
			return (stickDeadBand(-xBox_Driver.getRawAxis(GAMEPAD_XBOX_LEFT_Y_AXIS),.2));
		}else {
			return (stickDeadBand(xBox_Driver.getRawAxis(GAMEPAD_XBOX_LEFT_Y_AXIS),.2));
		}
		
	}
	public double driveLTigger(){
		return xBox_Driver.getRawAxis(GAMEPAD_XBOX_LEFT_TRIGGER);
	}
	public double driveRotation() {
		return stickDeadBand(xBox_Driver.getRawAxis(GAMEPAD_XBOX_RIGHT_X_AXIS),.2);
	}

	public boolean driveTurboMode() {
		return(xBox_Driver.getRawButton(GAMEPAD_XBOX_LEFT_BUTTON) || xBox_Driver.getRawAxis(GAMEPAD_XBOX_LEFT_TRIGGER)>0.2);
		
	}
	public boolean crawlBackward() {
        return(xBox_Driver.getRawButton(GAMEPAD_XBOX_A_BUTTON));
       
    }
	public boolean crawlForward() {
    	return(xBox_Driver.getRawButton(GAMEPAD_XBOX_Y_BUTTON));
    }
    
    public boolean crawlLeft() {
    	return(xBox_Driver.getRawButton(GAMEPAD_XBOX_B_BUTTON));
    }
    
    public boolean crawlRight() {
    	return(xBox_Driver.getRawButton(GAMEPAD_XBOX_X_BUTTON));
    }
    
    public double co_driveLTigger(){
		return xBox_CoDriver.getRawAxis(GAMEPAD_XBOX_LEFT_TRIGGER);
	}


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getxBox_Driver() {
        return xBox_Driver;
    }

    public Joystick getxBox_CoDriver() {
        return xBox_CoDriver;
    }

    public Joystick getlaunchPad() {
        return launchPad;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

